NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

default:
    resource: "@AppBundle/Controller/View"
    type:     annotation

api:
    resource: "@AppBundle/Controller/Api"
    type:     annotation
    prefix:   /api
