AppBundle\Entity\ArticleImage:
    type: entity
    table: article_image
    id:
        imageId:
            type: bigint
            nullable: false
            options:
                unsigned: false
            id: true
            column: image_id
            generator:
                strategy: IDENTITY
    fields:
        articleId:
            type: bigint
            nullable: false
            options:
                unsigned: false
            column: article_id
        featureImage:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: feature_image
        createdTime:
            type: datetime
            nullable: false
            column: created_time
        modifiedTime:
            type: datetime
            nullable: false
            column: modified_time
        latestEditor:
            type: bigint
            nullable: false
            options:
                unsigned: false
            column: latest_editor
        isVaild:
            type: boolean
            nullable: false
            column: is_vaild
    lifecycleCallbacks: {  }
