AppBundle\Entity\ArticleLike:
    type: entity
    table: article_like
    id:
        userId:
            type: bigint
            nullable: false
            options:
                unsigned: false
            id: true
            column: user_id
        articleId:
            type: bigint
            nullable: false
            options:
                unsigned: false
            id: true
            column: article_id
    fields:
        createdTime:
            type: datetime
            nullable: false
            column: created_time
        modifiedTime:
            type: datetime
            nullable: false
            column: modified_time
        lastestEditor:
            type: bigint
            nullable: false
            options:
                unsigned: false
            column: lastest_editor
        isValid:
            type: boolean
            nullable: false
            column: is_valid
    lifecycleCallbacks: {  }
